name: Daily Empty Commit
on:
  schedule:
    - cron: '*/5 * * * *' # 毎日午後0時（JST）に実行
jobs:
  daily-empty-commit:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create empty commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git commit --allow-empty -m "trigger daily deploy"
          git push origin ${{ github.ref }}
